import streamlit as st

# API KEYS
OPENAI_API_KEY = st.secrets["OPENAI_API_KEY"]
SLACK_WEBHOOK_URL = st.secrets["SLACK_WEBHOOK_URL"]

# Google Ads Auth
GOOGLE_DEVELOPER_TOKEN = st.secrets["GOOGLE_DEVELOPER_TOKEN"]
GOOGLE_CLIENT_ID = st.secrets["GOOGLE_CLIENT_ID"]
GOOGLE_CLIENT_SECRET = st.secrets["GOOGLE_CLIENT_SECRET"]
GOOGLE_REFRESH_TOKEN = st.secrets["GOOGLE_REFRESH_TOKEN"]
GOOGLE_LOGIN_CUSTOMER_ID = st.secrets["GOOGLE_LOGIN_CUSTOMER_ID"]
GOOGLE_CUSTOMER_ID = st.secrets["GOOGLE_CUSTOMER_ID"]

# Database
DATABASE_URL = st.secrets["DATABASE_URL"]